---
parser: babel-eslint
parserOptions:
  ecmaVersion: 8
  sourceType: module
extends:
- airbnb-base
- plugin:jest/recommended
- prettier
plugins:
- jest
- prettier
env:
  es6: true
  browser: true
  jest: true
  node: true
rules:
  import/no-extraneous-dependencies:
  - error
  prettier/prettier:
  - error
  - trailingComma: es5
    singleQuote: true
  jest/no-disabled-tests: warn
  jest/no-focused-tests: error
  jest/no-identical-title: error
  jest/valid-expect: error
  no-underscore-dangle: 0
  prefer-destructuring: 0
settings:
  import/resolver:
    babel-module: {}
