node6Environment: &node6Environment
  docker:
    - image: circleci/node:6@sha256:391562f18f8db926fd798680df42b3b9d057d0f960555ad874b31b623015f388
  working_directory: ~/nodejs
node8Environment: &node8Environment
  docker:
    - image: circleci/node:8@sha256:6fdf06edd413e742d9a4b7ea6ef3b38c99a761c4d8fd024c13d9b6e9080fd06d
  working_directory: ~/nodejs

aliases:
  - &restore_yarn_cache
    keys:
      - v1-yarn-cache-{{ checksum "yarn.lock" }}
      - v1-yarn-cache

  - &save_yarn_cache
    key: v1-yarn-cache-{{ checksum "yarn.lock" }}
    paths:
      - node_modules

  - &yarn_install
    name: Installing
    # Ignoring scripts (e.g. post-install) to gain more control
    # in the jobs to only e.g. build when explicitely needed.
    command: yarn install --pure-lockfile --ignore-scripts

  - &yarn_bootstrap
    name: Bootstraping
    # Limiting the default concurrency (4) of lerna to 2
    # as the build otherwise dies due to resouce restrictions.
    command: yarn bootstrap --concurrency=2

  - &yarn_build
    name: Building
    command: yarn build

  - &unit_test
    name: Unit testing
    # Limiting the workers of Jest to 10
    # as the build otherwise dies due to resouce restrictions.
    command: yarn test:ci --maxWorkers=10

  - &unit_test_with_coverage
    name: Unit testing (with coverage report)
    command: yarn test:coverage:ci

version: 2
jobs:
  lint:
    <<: *node8Environment
    steps:
      - checkout
      - restore-cache: *restore_yarn_cache
      - run: *yarn_install
      - run: *yarn_bootstrap
      - run: *yarn_build
      - save_cache: *save_yarn_cache
      - run:
          name: Linting
          command: yarn lint
  test_unit_node_6:
    <<: *node6Environment
    steps:
      - checkout
      - restore-cache: *restore_yarn_cache
      - run: *yarn_install
      - run: *yarn_bootstrap
      - run: *yarn_build
      - save_cache: *save_yarn_cache
      - run: *unit_test
  test_unit_node_8:
    <<: *node8Environment
    steps:
      - checkout
      - restore-cache: *restore_yarn_cache
      - run: *yarn_install
      - run: *yarn_bootstrap
      - run: *yarn_build
      - save_cache: *save_yarn_cache
      - run: *unit_test_with_coverage

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
      - test_unit_node_6:
          requires:
            - lint
      - test_unit_node_8:
          requires:
            - lint
